src/browser.ts
src/page.ts

feat: url property to page

---

src/browser.ts
src/page.ts
src/util.ts

feat: allow for multiple browsers

---

src/page.ts
tests/evaluate_test.ts
tests/stealth_test.ts

feat: page.setViewportSize

---

src/browser.ts
src/page.ts
tests/event_test.ts

feat: add console and pageerror events

---

src/cache.ts

fix https://github.com/lino-levan/astral/issues/37

feat: use dirs module to get the defaut cache dir locaion

---

src/cache.ts
src/element_handle.ts
tests/existing_ws_endpoint_test.ts
tests/install_lock_file_test.ts
tests/query_test.ts

Originally reported on discord.

fix: bug in `element.$(selector)` and bump std

---

deno.jsonc

See https://jsr.io/@astral/astral

fix: icon not visible on JSR readme

---

src/page.ts
tests/locator_test.ts
tests/navigation_test.ts

What it says on the tin. Necessary for #61.

feat: `page.goBack` and `page.goForward`

---

src/page.ts

chore: make it so `page.url` is never undefined

---

src/page.ts

feat: infer return type in evaluate

---

deno.jsonc
src/browser.ts

chore: expose celestial bindings on the browser

---

README.md

Requested by Bartek on discord.

chore: rewrite readme to add more examples and temporarily remove docs

---

src/page.ts
tests/query_test.ts

feat: emulate media features

---

src/browser.ts

chore: better error message on missing system dependencies

---

src/browser.ts

fix: support user provided `--user-data`

---

src/browser.ts

Disconnect on disposal if using Websockets

---

src/debug.ts

fix: do not die on DEBUG variable env permissions not granted

---

src/browser.ts

Added custom browserContext for each session

---

src/cache.ts

For https://github.com/lino-levan/astral/issues/117
If the download of chrome is interrupted unexpectedly, lock file will be retained forever.
We need to clean abnormal lock file

Abnormal lock file needs to be cleared

---

.github/workflows/ci.yml
README.md
examples/authenticate.ts
src/page.ts

Same as https://pptr.dev/api/puppeteer.page.authenticate

feat(authenticate): Provide credentials for HTTP authentication

---

.github/workflows/ci.yml
README.md
examples/authenticate.ts
src/page.ts
tests/authenticate_test.ts

For https://github.com/lino-levan/astral/pull/125

feat(authenticate): Provide credentials for HTTP authentication & Fix "No usable sandbox!" with user namespace cloning enabled

---

src/debug.ts

fix: astral in deploy crashing due to querySync

---

src/browser.ts

chore: improve stealth

---

src/element_handle.ts

fix: element screenshot to include borders and add scale option 

---

src/keyboard/mod.ts
src/mouse.ts
src/page.ts
src/touchscreen.ts
tests/keyboard_test.ts

fix: modifier key with mouse and touch events

---

src/element_handle.ts
src/locator.ts
src/mouse.ts
tests/mouse_test.ts

Title. Also added mouse tests since we were missing those.

feat: add mouse options to locator and element handle click

---

README.md
docs/pages/advanced/connect.md
docs/pages/index.md
src/browser.ts
tests/dialog_test.ts
tests/existing_ws_endpoint_test.ts
tests/mouse_test.ts

Title. Also fixes some typos and hopefully fixes flaky tests.

feat: launch browser from http endpoint
