lino-levan/astral

src/page.ts, tests/set_content_test.ts
Implement `page.setContent()` method
Mostly ported from 
https://github.com/puppeteer/puppeteer/blob/067a5b290083adcb297231ed360cec27ce2e4155/packages/puppeteer-core/src/common/util.ts#L554-L565
=> feat: add `page.setContent`

src/browser.ts
The singleton lock of chrome may already been removed during the time the message was receive and the process closing.
This prevents dying if it was already cleaned before astral has the time to do it
=> fix: don't crash if chrome singletonlock is already removed after detection

src/browser.ts, src/cache.ts, tests/get_binary_test.ts
Small patch to avoid requiring `--allow-env` permissions (which is used to compute default cache path) when a cache path is manually specified by end user
=> fix: don't require --allow-env perms when cache param is specified

docs/pages/advanced/sandbox.md, src/browser.ts, src/cache.ts, src/page.ts, tests/get_binary_test.ts, tests/sandbox_test.ts
Towards #33
This adds a `sandbox` parameters to `browser.newPage()`:
- If `sandbox: true`, each network request is intercepted and checked against deno permissions
- If `sandbox: Network_ResourceType[]`, only network requests matching the resource type are intercepted and checked against deno permissions (for example, you can choose to just sandbox `document` or `fetch`  request)
Unfortunately because of https://github.com/denoland/deno/issues/14668, I had to add a `sandboxPrompt` arg to toggle interactivity, since the current `Deno.permissions.request` will always ask for permissions even when passing `--no-prompt` or with `DENO_NO_PROMPT=1`
From the unit test I added, it seems pretty robuts, as you even if you try to use `page.evaluate` to redirect or fetch with JS, the network request …
=> feat: support sandbox mode

deno.jsonc, src/element_handle.ts, src/page.ts, tests/wait_test.ts
Currently the `waitForSelector` method does not work as expected, the method **never fails** since the validation of the while loop is not precise (`this.#celestial.DOM.querySelector()` always returns an object even if the node is not found).
Therefore, this change suggests a modification in the validation and the implementation of a custom timeout by the user.
=> chore: enhancement waitForSelector method

src/element_handle.ts
There are corner cases where the result is `undefined`, it is proposed to change the validation to avoid internal errors
Tests
=> chore: enhancement $ method to avoid internal errors

src/browser.ts, src/page.ts, tests/resource_test.ts
Add support for disposing of `Page` and `Browser` instances with the `using` keyword. It's part of https://github.com/tc39/proposal-explicit-resource-management and it's natively supported in Deno. Allows you to write code like this:
```ts
Deno.test("my test", async () => {
await using browser = await launch();
await using page = await browser.newPage();
// No need to manually call page.close() and browser.close()
})
```
=> feat: support async disposing of `Page` and `Browser`

src/page.ts
Looks like a typo sneaked into the event names. This meant that we were never removing the event listeners as the event names didn't match which caused timers to leak.
See https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent
=> fix: incorrect event names in `waitForNetworkIdle`

docs/pages/guides/navigation.md, examples/navigation.ts, src/page.ts, tests/wait_test.ts
Move `waitForNavigation` calls to the top of the  `Promise.all` array to ensure that listeners are set up first before triggering the action. I remember that this was a prominent issue in the early puppeteer days and hopefully that fixes the macOS CI errors.
=> fix: ensure navigation listeners are setup before trigger

src/locator.ts, src/page.ts, tests/fixtures/counter.html, tests/fixtures/evaluate.html, tests/fixtures/wait_for_element.html, tests/locator_test.ts
This PR adds a basic locator API. It doesn't have all the additional checks that `puppeteer` has yet as it's based on the existing `Page` methods apart from waiting for the selector.
But that alone makes tests a little simpler to write. And we can always iterate further based on this.
```ts
// before
await (await page.$(".trigger"))!.click();
// after
await page.locator(".trigger").click();
```
```ts
// before
const text = await (await page.$("pre"))!.evaluate(el => el.textContent!);
// after
await page.locator("pre").evaluate(el => el.textContent);
```
Related https://github.com/lino-levan/astral/issues/2
=> feat: add basic locator API

src/locator.ts, tests/fixtures/fill.html, tests/locator_test.ts
=> feat: locator.fill

src/element_handle.ts
Minor DX improvement: When a `waitForSelector` call fails to find the selector it should include the selector in the error message.
=> fix: print selector on locator failure

src/page.ts
=> fix(sandbox): use `request` instead of `query` for Deno permissions

src/browser.ts
I was surprised to see that playwright doesn't have this (https://github.com/microsoft/playwright/issues/4956). Looks like we'll have to defer to puppeteer's judgement here.
=> fead: add `Browser.disconnect` method

.github/workflows/ci.yml, .github/workflows/publish.yml, docs/pyro.yml, tests/fixtures/fill.html, tests/locator_test.ts
location_test was failing with the following message.
```
*  Executing task: C:\ProgramData\chocolatey\lib\deno\deno.EXE test --allow-all --no-check --trace-leaks --filter /^Locator - click\(\)$/ d:\Repos\jeiea\2024\09\astral\tests\locator_test.ts 
running 1 test from ./tests/locator_test.ts
Locator - click() ... FAILED (8s)
ERRORS 
Locator - click() => ./tests/locator_test.ts:39:6
error: RetryError: Retrying exceeded the maxAttempts (5).
throw new RetryError(error, options.maxAttempts);
^
at retry (https://jsr.io/@std/async/0.223.0/retry.ts:143:15)
at eventLoopTick (ext:core/01_core.js:175:7)
at async Locator.click (file:///D:/Repos/jeiea/2024/09/astral/src/locator.ts:24:5)
at async file:///D:/Repos/jeiea/2024/09/astral/tests/locator_test.ts:46:3
Caused by: Error: Unable to get stable …
```
=> feat: deno v2

deno.jsonc, tests/dialog_test.ts, tests/element_evaluate_test.ts, tests/evaluate_test.ts, tests/event_test.ts, tests/existing_ws_endpoint_test.ts, tests/get_attributes_test.ts, tests/get_binary_test.ts, tests/locator_test.ts, tests/navigation_test.ts, tests/query_test.ts, tests/resource_test.ts, tests/sandbox_test.ts, tests/set_content_test.ts, tests/wait_test.ts
Fork from #98 and fix import paths for tests.
=> chore: update dependencies

deno.jsonc, src/cache.ts
Close #102
```bash
#!/bin/bash
rm -rf /home/codespace/.cache
echo "STDOUT: $(deno run -A test.ts)"
```
```shell
Downloading chrome 125.0.6400.0                                                    100.00%
Download complete (chrome version 125.0.6400.0)
Inflating /home/codespace/.cache/astral/125.0.6400.0                                         100.00%
Browser saved to /home/codespace/.cache/astral/125.0.6400.0
STDOUT: /home/codespace/.cache/astral/125.0.6400.0/chrome-linux64/chrome
=> fix: print download progress to stderr

examples/user_agent.ts, src/browser.ts, src/page.ts
What it sounds like, more or less.
I'm still figuring out how exactly the page-level bindings work, and this could maybe use some new tests, but in the meantime here's a sketch of how I'm envisioning the browser-level handling
=> Feat: user defined user agent

README.md
At some point in the past, we separated out `launch` and `connect` (since there are options that make sense for one but not the other). This PR updates the documentation to reflect that reality.
=> docs: update to include connect

src/page.ts, tests/leak_test.ts
Should fix https://github.com/denoland/fresh/pull/2901
=> fix: leaky page close

docs/pages/advanced/sandbox.md, src/debug.ts, src/page.ts, tests/sandbox_test.ts
Close #116 
Support `<script>` (`resourceType === "Script"`) validation in sandbox mode against `--allow-import` permissions
=> feat(sandbox): implement script permissions checks with --allow-import

deno.jsonc, docs/pages/showcase.tsx, src/locator.ts, tests/locator_test.ts
I would find it useful to be able to access descendants from a Locator. This PR adds methods to help with that.
=> feat: locator descendants
